### ISSUE TITLE
Entry point naming convention

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#10]
It is required that VM implementations have different names for "create" function.
At the moment we recommend naming them as `<vm-name>_create`.
I'd like to change the convention to `evmc_create_<vm-name>`.

This name would be more distinctive and will contain `evmc_` prefix to easier recognize that it is for.
Also, when loading dynamic library I'm considering iterating over all exported symbols searching for `evmc_create_` prefix.

**Comment by axic** [comment]
> Also, when loading dynamic library I'm considering iterating over all exported symbols searching for evmc_create_ prefix.

That makes sense, in that case the name doesn't need to be tied to the file name.

**Comment by ehildenb** [comment]
Why is it required that VM implementations have different names for "create" function?

Otherwise the naming scheme looks fine.

**Comment by ehildenb** [comment]
Well, actually, is it required that different versions of a VM have different names for "create" as well? Because how would this account for that?

**Comment by chfast** [comment]
Different symbol names are required to allow having more than single implementation statically linked in a client.

**Comment by ehildenb** [comment]
So I guess could you possible have multiple versions of a single VM statically linked to a client? If we support versioned ewasm, then I think so.

**Comment by chfast** [comment]
I think having 2 version of the same VM implementation (e.g. Hera) will be hard, unless you name the functions `evmc_create_hera1` and `evmc_create_hera2`.

But you can have different versions of Hera as shared libs.

**Comment by axic** [comment]
I think with `dlopen` style loading it is possible to have conflicting symbols loaded, so it would be possible to load multiple versions of Hera.

But the main point of the unique naming is static linking.

**Comment by chfast** [comment]
So can I consider `evmc_create_` convention as accepted?

**Comment by axic** [comment]
I'm fine with it. During dynamic loading it doesn't matter if it is a prefix or a postfix, though probably a prefix is more natural.

**Comment by axic** [comment]
@chfast are you creating a change for this?

**Comment by chfast** [comment]
Trying to finish base migration for Hera first.
