### ISSUE TITLE
set_option to have more response codes (success, fail, invalid option, invalid value)

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#102]
Suggestion:
- 0: success
- 1: failure (general)
- 2: invalid option
- 3: invalid value for option

Perhaps it should return an enum?

**Comment by axic** [comment]
@chfast any opinion?

**Comment by chfast** [comment]
I think it is fine as it is.

**Comment by axic** [comment]
I think this is important to be improved, because it improves error reporting a lot and clients can show: "unknown option", "invalid value option", etc. Currently all of them can only resort to a compound catch all message: "option not found or invalid".
