### ISSUE TITLE
Review Host callbacks return types

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#117]
- [ ] `get_balance()`, `get_code_size()`, `get_code_hash()`.
   This should not return `int` to inform if an account exists. It would make it unnecessary complicated and a VM usually does not care (a contract might, but usually don't).

**Comment by axic** [comment]
> `get_balance()`, `get_code_size()`, `get_code_hash()`.
>   This should not return `int` to inform if an account exists. It would make it unnecessary complicated and a VM usually does not care (a contract might, but usually don't).

Based on the latest discussions it makes sense to keep these returning a boolean, just like `get_block_hash` is working, but with a slight change: if it returns false, it should not modify the supplied result pointer.

**Comment by axic** [comment]
The same should apply to `get_storage`/`set_storage`.

**Comment by chfast** [comment]
Handle set_storage and get_storage separately in https://github.com/ethereum/evmc/issues/146.
