### ISSUE TITLE
Rename evmc_uint256be to evmc_bytes32 to reflect its content better

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#121]
This of course means for price values `evmc_uint256be` needs to be added back, but `storage_set`/`storage_get`/`hashes` `evmc_bytes32` would be used.

**Comment by chfast** [comment]
This comes down to https://github.com/ethereum/evmjit/issues/110.

**Comment by axic** [comment]
@chfast @gumb0 suggested to use `typedef`. Need to check if rust-bindgen likes that.
