### ISSUE TITLE
Implement caching proxy

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#126]
This could be used as for caching both code translation (evmjit) and host access.

It should be implemented as an EVMC VM while also loading another VM and proxying between the two.

**Comment by chfast** [comment]
This is on consensus critical path so it would need to know some Ethereum specific rules. Moreover, the caching strategy is DoS attack vector. And clients have the cache anyway.

**Comment by axic** [comment]
@chfast is this still a relevant issue? I suggest closing.
