### ISSUE TITLE
Introduce enum evmc_bool

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#131]
In https://github.com/ethereum/evmc/blob/master/include/evmc/evmc.h#L164 `evmc_block_hash_fn` returns 1 on success, 0 on failure.

Compared to that, `evmc_status_code` uses the POSIX style 0 for success, anything else for failure.

This kind of indicates an inconsistency. `evmc_block_hash_fn` tries to map a boolean into a uint, that's why.

A solution could be either using `stdbool.h` or creating an enum to replicate it: `evmc_bool`.

**Comment by chfast** [comment]
I considered this and I'm not convinced because I'm not sure we should introduce another bool type.

**Comment by axic** [comment]
`stdbool.h`: http://pubs.opengroup.org/onlinepubs/009604499/basedefs/stdbool.h.html, not sure which C standard introduced it.

**Comment by axic** [comment]
Should check `stdbool.h` with Go and rust-bindgen.

**Comment by chfast** [comment]
The `stdbool.h` is good for:
- Visual Studio
- Go
- Python CFFI
- Rust.

I will try this one.
