### ISSUE TITLE
Create Java (JNI) binding

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#137]
Could help with https://github.com/ethereum/ethereumj/issues/1025

**Comment by ajsutton** [comment]
It's looking increasingly likely that at least some of the crypto-heavy precompiles will wind up centralised on a single implementation for performance reasons which would make something like this a requirement.

To be honest I can't see the PegaSys team finding time time to work on this in the near future - I'd like to it's just there's a huge number of competing things a new client like Pantheon needs to work on.

**Comment by axic** [comment]
I understand, thanks for the response. Still hoping some time in the future it will be picked up :wink:

**Comment by axic** [comment]
Apparently here's an (slightly outdated) implementation: https://github.com/semuxproject/evmc-jni

**Comment by jrhea** [comment]
@axic i am pretty close to having this done. see pr #455

**Comment by axic** [comment]
Found this implementation too: https://github.com/semuxgo/evmc-jni
