### ISSUE TITLE
Enforce "debug" or "verbose" option to be supported by all VMs

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#142]
From https://github.com/ethereum/evmc/pull/136#issuecomment-419036254:

The `debug` or `verbose` option (pick one) should be required by all VMs. Accepted values should be `on` or `off`.

**Comment by axic** [comment]
@chfast any comments?

**Comment by chfast** [comment]
I don't want to enforce them.

We can specify some "standard" options so if a VM implement any of them it should follow the specification. But I think it's too early for that.
