### ISSUE TITLE
Return bool from get_storage and set_storage

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#146]
Continuation of #117 

### get_storage

For `get_storage` we can do similarly to `get_code_hash` and return `false` when an account does not exist, but this is very artificial case, because the `get_storage` is only used for the currently executed account. Any VM should not expect `get_storage` to fail.

### set_storage

Similar story as for `get_storage` but worse. The `set_storage` returns `evmc_storage_status`. This one would need to be extended with `EVMC_STORAGE_NO_SUCH_ACCOUNT`.

**Comment by axic** [comment]
I think this still makes sense because the function still has an `address` parameter. What to do if a VM uses an another address? Not clear.

**Comment by chfast** [comment]
Is the documentation enough then?

**Comment by axic** [comment]
`set_storage` should have that `NO_SUCH_ACCOUNT` case.

I guess we can go with that for the moment, but if we do have `NO_SUCH_ACCOUNT`, we may just want to have the bool in `get_storage` and the design pattern is that we use `bool` where appropriate, but if the function needs more cases than `true/false`, then use an enum such as `set_storage` is doing.
