### ISSUE TITLE
Move C++ bindings from aleth to here (helpers for clients)

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#156]
~~At least the wrapper over Result: https://github.com/ethereum/aleth/blob/master/libevm/EVMC.h#L17-L71~~

But preferably also the context wrapper: https://github.com/ethereum/aleth/blob/master/libevm/ExtVMFace.h#L203-L279

**Comment by chfast** [comment]
I tried that. It is much more complex than code move.

**Comment by chfast** [comment]
First part is done.
