### ISSUE TITLE
New status code `EVM_EC_ERROR`

### ISSUE THREAD

**Issue by ehildenb** [ethereum/evmc#16]
This test: https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/stZeroKnowledge2/ecadd_0-0_1-3_21000_128_d0g0v0.json

throws exceptions in KEVM during some elliptic curve math. Currently, I am reporting elliptic curve errors as `EVM_INTERNAL_ERROR`, which does not count as an "exceptional" error but a VM failure. However, the test indicates that it should be treated as an "exceptional" error. See here (search for `EVM_INTERNAL_ERROR`): https://github.com/kframework/evm-semantics/blob/typed-exceptions/evm.md#precompiled-contracts

When running this using `./kevm run tests/ethereum-tests/BlockchainTests/GeneralStateTests/stZeroKnowledge2/ecadd_0-0_1-3_21000_128_d0g0v0.json`, it indicates that it reaches:

```
<statusCode> EVM_INTERNAL_ERROR </statusCode>
<k> #exception ~> #return ... </k>
```

which basically means "if it's an exceptional error, handle it correctly", but because it's being reported as an `EVM_INTERNAL_ERROR`, execution halts and the test now fails.

I propose adding `EVM_EC_ERROR`, which indicates errors in the elliptic curve crypto functions.

**Comment by ehildenb** [comment]
Or perhaps more generally, `EVM_PRECOMPILE_ERROR`?

**Comment by chfast** [comment]
So you returns `EVM_INTERNAL_ERROR` from a call to a precompiled contract instead of `EVM_FAILURE`?

I'm fine with adding `EVM_PRECOMPILE_FAILURE` (following Java naming convention when Error are not recoverable).

Can you make a PR with this?

**Comment by axic** [comment]
Keep in mind that on the "real EVM" there is no distinction between these errors, because there is no way to retrieve anything past "success or failure" via `CALL` or external transaction.
