### ISSUE TITLE
Release version 0.1.0 matching ABI v1

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#20]

**Comment by axic** [comment]
Do you suggest that `x.y.z` corresponds to
- x = fixed at 0
- y = matches the ABI version
- z = patch level?

Or we'll come up with two disparate set of versions vs. abi versions?

I was wondering if we should just tag the releases as `abi-1`, `abi-2`, but then question is: does it correspond to the first time the new abi was added? What about patches to it? `abi-1.0`, `abi-1.1`, ... ?

As a result I think we should go with semver x.y.z where x corresponds to the ABI version, that means we are 3.0.0 now.

Which I guess could be reasonable (3 major breaking releases) in the last 3 years evmc existed.

**Comment by chfast** [comment]
I'm not sure. I'd rather map it like this
```
v0.1 - ABI v1
v0.2 - ABI v2
v0.3 - ABI v3
```
Then at some point release v1.0.

Also the ABI version could be `100 * major_version + minor_version`.

**Comment by axic** [comment]
What is a 1.0 release?

I like semver because it fixes this question by removing the vanity aspect of version numbers.

**Comment by gumb0** [comment]
Semver looks like less thinking to decide when we go to 1.0, then 2.0 etc.

**Comment by gumb0** [comment]
BTW if "Net gas metering for SSTORE" EIP makes it into Constaninople, it will require another change I think - a function for VM to request whether storage slot is "dirty"

**Comment by chfast** [comment]
The semver is something that is mentioned a lot but nobody is using it in the end.

**Comment by axic** [comment]
Everybody is using it outside of C++ space 😉

**Comment by chfast** [comment]
For 1.0 I'd like to have all missing changes that are currently planned, i.e. Constantinople support, two-phase initialization (makes Go bindings easier) and Go bindings.

So far I'd like to make 0.x releases following semver option for "development" releases.

I think it would be simpler to use two numbers instead of three in the full version number.

**Comment by axic** [comment]
I'm not sure what Constantinople, etc. has to do with the "magical 1.0".

I think EVMC is a rolling API and I'd strongly suggest to go with the stable version of evmc (it is not development mode anymore), that is we are at `5.0` (ABIv5). I think it makes a lot of sense that the major is matching the ABI version, it removes a lot of ambiguities. (A: I'm using EVMC 1.22. B: Hm, is that the one with ABIv10 or ABIv11?)

**Comment by chfast** [comment]
Ok then, but can I use `5.0` numbering instead of `5.0.0` numbering?

**Comment by axic** [comment]
I'm not sure about that, but I'd assume if it is truncated, one assumes the patch level is 0. I don't care if it is 5.0 or 5.0.0.

According to http://jubianchi.github.io/semver-check/ it seems the 3 digits are required.
