### ISSUE TITLE
Add evmc to Hunter

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#214]

**Comment by axic** [comment]
Can versions be pinned when using Hunter?

**Comment by chfast** [comment]
Yes.

**Comment by chfast** [comment]
I believe we have to put it on hold because of https://github.com/ruslo/hunter/issues/1921.

**Comment by axic** [comment]
Is Hunter still maintained? I recall something going on around it.

**Comment by chfast** [comment]
Hunter is fine. But I'm sure this is useful. I like to have evmc as a git submodule / CMake subproject in other projects, because this makes EVMC development and cross-checking easier (this model is also possible in Hunter as you can specify any commit EVMC repo to use, it is just less convenient as you need to specify the commit hash manually).

**Comment by axic** [comment]
Close this then?
