### ISSUE TITLE
Add asan to vmtester tests

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#239]

**Comment by axic** [comment]
@chfast would this be a big chunk of work? It would be nice to verify that none of the examples (C++, Rust) are leaking memory.

**Comment by chfast** [comment]
It is a small configuration mess. I think you should instrument both vmtester and examples to make sure vmtester does not have issues on its own. It might also help with invoking tests (no need for manual ASan library preload).
Then you must make sure that the instrumented vmtester is not the one published as a release.

Is it easy to build rust with ASan? I can handle the C/C++ part of it.

**Comment by axic** [comment]
The rust part is taken care of in #312. @chfast do you want to do the rest? Is it useful?

**Comment by chfast** [comment]
> @chfast do you want to do the rest? Is it useful?

I think this is maintenance mess because there are (number if sanitizers) x (number of LLVM versions) combinations to have. I believe the only reasonable solution is to build EVMC from source if you need instrumentation.

**Comment by chfast** [comment]
Can I close it?
