### ISSUE TITLE
Rust bindings are incompatible with EIP-2003

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#318]
[EIP-2003](https://github.com/ethereum/EIPs/pull/2003) states that `code` and (host) `context` is not mandatory for precompiles and can be null, but the Rust bindings assert for the presence of both.

**Comment by chfast** [comment]
For code, we don't disallow null pointers. We can clarify that the pointer cannot be if the size is non-zero. You will be always allowed to pass empty code.

Context is actually two things: 
- the pointer to additional data Host wants to keep with given execution (the real context), this can always be empty,
- the Host interface (vtable with methods).
These two are going to be split in the next version of EVMC, but it still do not solve the problem entirely. 

Anyway, I think this is fine for now while we don't have any EVMC precompiles.

**Comment by axic** [comment]
It should be clarified in `evm.h` because it doesn't say anything about these fields.
