### ISSUE TITLE
Create a library out of example_host

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#334]
The `example_host` already implements a lot of what a minimal client for testing needs.

It may make sense creating a library out of it, so that it could be shared with Solidity. This library could be provide a C++ interface wrapping everything needed for testing (aka a memory-only single node client).

@chfast @chriseth what do you think?

**Comment by chfast** [comment]
To bad idea, I already use it for EVMC testing.

**Comment by axic** [comment]
> To bad idea, I already use it for EVMC testing.

Too bad?

**Comment by chfast** [comment]
> > To bad idea, I already use it for EVMC testing.
> 
> Too bad?

~~To~~Not. I should not work at nights.

**Comment by chfast** [comment]
Here is more functional one: https://github.com/ethereum/evmone/blob/master/test/utils/host_mock.hpp
Used for evmone unit testing and EVM fuzzing.

**Comment by axic** [comment]
The Solidity version of this is here:
- https://github.com/ethereum/solidity/blob/develop/test/EVMHost.cpp
- https://github.com/ethereum/solidity/blob/develop/test/EVMHost.h
