### ISSUE TITLE
Rename: evmc-vmtester to evmc-check-compatibility

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#336]
The name `evmc-vmtester` suggests it actually tests the EVM implementation.

Suggested names:
- `evmc-check-compliance`
- `evmc-check-vm-compliance`
- `evmc-compliance-check`
- `evmc-vm-compliance-check`
- `evmc-check`
- `evmc-check-vm`
- `evmc-vm-check`

I'm rather for going less pedantic and avoid `-vm-` part. If we could figure out how to test Host compatibility, it could be included in the same tool.

**Comment by axic** [comment]
I don't think it suggests testing EVM, but it definitely tests VMs and not Hosts.

**Comment by gumb0** [comment]
`evmc-compatibility-check` sounds good to me

**Comment by gumb0** [comment]
(maybe it checks "compliance to EVMC" rather than compatibility?)

**Comment by chfast** [comment]
> (maybe it checks "compliance to EVMC" rather than compatibility?)

That's absolutely right. The list updated.

I now like `evmc-check` the most, the `evmc-check-vm` would be the second choice.

**Comment by axic** [comment]
So what is the decided name?

**Comment by chfast** [comment]
I'm leaving the name for now as it do not affect the CMake helper.
