### ISSUE TITLE
Consider rewriting example_vm in C++

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#364]
See https://github.com/ethereum/evmc/pull/362#issuecomment-514166440

**Comment by chfast** [comment]
The example_vm should stay as a single C file. It is very useful for language bindings integration testing (e.g. just load any VM and check if you can get the name of it).

It can be built with one-liner:
```
gcc -shared -I../../include ../../examples/example_vm/example_vm.c -o example-vm.so
```
And it is more likely to have C compiler available in the testing environment than C++ compiler.

**Comment by axic** [comment]
I think the reason we wanted it to showcase the C++ bindings. It would make sense to have a C++ version for that reason.

Btw wouldn't the release contain the builds?
