### ISSUE TITLE
Document that evmone has an EVM unit test tool for EVMC VMs

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#387]
@chfast do you think this makes sense?

**Comment by chfast** [comment]
Yes.

**Comment by chfast** [comment]
But maybe wait until evmone 0.2 to have a binary people will be able to download.

**Comment by axic** [comment]
Moved this to 6.4. I think we should make a 6.4 release with some final (non-breaking) fixes/changes before 7.

**Comment by axic** [comment]
@chfast I think this could be done now since evmone 0.2.0 was released.
