### ISSUE TITLE
Calculate refunds on VM side

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#413]
It should be VM's responsibility to calculate and aggregate refunds.

- [ ] Add "refund" filed to `evmc_result`.

**Comment by axic** [comment]
[daytona](https://github.com/axic/daytona/) depends on this.

**Comment by jlokier** [comment]
Nowadays refunds depend on information only known by the Host when the EVM calls `setStorage`, and I think that's quite a neat separation of concerns and knowledge. So perhaps this issue should be closed.

**Comment by chfast** [comment]
We are providing a lot of information about the SSTORE status to allow proper gas counting inside VM: https://github.com/ethereum/evmc/blob/master/include/evmc/evmc.h#L510-L536. There may be cases not handled by this where gas cost is the same but the refund is different, but I don't think we need very different mechanism to handle it fully.
