### ISSUE TITLE
EVMC does not compile in Visual Studio 2019

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#416]
The problem is in C++ user-defined literals.
Reproduced here: https://ci.appveyor.com/project/chfast/evmc/builds/27017625/job/uhjsf9gs5b7gc95s
Compiler bug: https://developercommunity.visualstudio.com/content/problem/553839/vs-2019-incorrect-partial-template-specialization.html

**Comment by halfalicious** [comment]
[Visual Studio 2019 Preview 2](https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes-preview#16.3.0-pre.2.0) has the fix for this bug, I've verified that it addresses the issue (I can build EVMOne fine with it)

**Comment by chfast** [comment]
We are waiting for 16.3 release then. Before closing this, add a check to CMake that would inform user that 16.3 is required to properly build this.

**Comment by chfast** [comment]
The 16.3 has been released and it builds fine.

**Comment by halfalicious** [comment]
@chfast: will add the cmake check soon
