### ISSUE TITLE
Add "runner" tool to execute VMs

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#447]
Basically the equivalent of "evmbin" many clients have.

This could start simple with only accepted two inputs:
- bytecode to run
- calldata

And hardcoding everything else. Later it could be extended to accept more settings or even store the state in a yaml/json file (aka genesis).

This would reuse `examples/example_host.c` and I'd call the tool `evmc-runner` and place it into `test/runner` or `tools/runner`.

**Comment by chfast** [comment]
This sounds good, but I'm not sure I want to add more dependencies to this project. And also it duplicates some work at least from `evmone-bench`.

**Comment by axic** [comment]
I'd need this for Hera and it is awkward getting "EVMC tools" from evmone.
