### ISSUE TITLE
EVMC_EXPORT for GNUC<4 and Mingw?

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#47]
`utils.h` defines `EVMC_EXPORT` as:
```
#ifdef _MSC_VER
#define EVMC_EXPORT __declspec(dllexport)
#else
#define EVMC_EXPORT __attribute__((visibility("default")))
#endif
```

but Hera does the following:
```
#if defined _MSC_VER || defined __MINGW32__
# define HERA_EXPORT __declspec(dllexport)
# define HERA_IMPORT __declspec(dllimport)
#elif __GNU__ >= 4
# define HERA_EXPORT __attribute__((visibility("default")))
# define HERA_IMPORT __attribute__((visibility("default")))
#else
# define HERA_EXPORT
# define HERA_IMPORT
#endif
```

Two differences:
- supporting MINGW32
- checking for GNUC>=4

Do we want these here?

**Comment by chfast** [comment]
1. We want mingw32.
2. We don't want to support GCC 3 :) It will not be able to compile any of our projects anyway.
3. __declspec(dllimport) is only needed for C++ classes and maybe globals, so we don't need it. And HERA_IMPORT is done incorrectly anyway.
