### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#475]
Should consider publishing the Rust crates.

@chfast any comments?

**Comment by chfast** [comment]
Fine to me if that helps.

**Comment by axic** [comment]
Published:
- https://crates.io/crates/evmc-sys
- https://crates.io/crates/evmc-vm
- https://crates.io/crates/evmc-declare

**Comment by chfast** [comment]
So this is manual work?

**Comment by axic** [comment]
Yes. Need to run `cargo publish` in each of these directories at a release.
