### ISSUE TITLE
using bool from stdbool.h makes FFI author life difficult

### ISSUE THREAD

**Issue by jangko** [ethereum/evmc#494]
why is it difficult:
- there is nowhere in documentation of C guarantee the size of `bool`. is it a byte or is it an int?
- there is no guarantee a `bool` in one language will have the same size with `bool` from C language.
- not all language FFI mechanism have access to C implementation specific feature.

please reconsider using a `fixed-size` replacement for `bool`. 

EDIT: size_t have different size on 32 bit vs 64 bit platform. but it is well defined and well documented. In other hand a `bool` in `stdbool.h` does not have size definition.

**Comment by chfast** [comment]
Do you have any particular FFI project in mind?

**Comment by chfast** [comment]
Anyway, as far as the standard is concerned, even `int` type may have different size than 4. Similarly for enums.
But in practice the `sizeof(_Bool)` is 1: https://godbolt.org/z/marD9R

The problematic type is usually `long` which can be 4 or 8, depending on the compiler.

**Comment by jangko** [comment]
> Do you have any particular FFI project in mind?

we are working to implement EVMC interface for [nimbus](https://github.com/status-im/nimbus)

> Anyway, as far as the standard is concerned, even int type may have different size than 4. Similarly for enums.

this is documented and well known behaviour since C89

> But in practice the sizeof(_Bool) is 1: https://godbolt.org/z/marD9R

we are lucky then

I think such agreement between C compilers will pose little risk in the future.
thanks for your help. closing this issue.

**Comment by axic** [comment]
> we are working to implement EVMC interface for nimbus

Please also check out #157.
