### ISSUE TITLE
Add support for EIP-1087: Net storage gas metering for the EVM

### ISSUE THREAD

**Issue by chfast** [ethereum/evmc#50]
I propose to extend the function `evmc_set_storage()` by returning additional information to

```c
enum evmc_storage_status evmc_set_storage(
    struct evmc_context* context,
    const struct evmc_address* address,
    const struct evmc_uint256be* key,
    const struct evmc_uint256be* value
);
```

The `enum evmc_storage_status` would contain the information what happened with the storage, like
- unmodified,
- modified,
- added,
- deleted,
- modified_dirty.

The gas cost is going to be applied after the `evmc_set_storage()` is executed (is this a problem?).

This also avoids calling `evmc_get_storage()` first.

**Comment by chfast** [comment]
cc @arachnid

**Comment by gumb0** [comment]
The EIP suggessts different costs when the slot is modified for the first time in transaction vs subsequent modification in the same transaction, so I think this proposal doesn't cover this difference.

**Comment by chfast** [comment]
cc @arachnid

**Comment by chfast** [comment]
> The EIP suggessts different costs when the slot is modified for the first time in transaction vs subsequent modification in the same transaction, so I think this proposal doesn't cover this difference.

You are right. I didn't wanted to make it so much detailed. I meant "include any distinctive storage status need to implement Constantinople".

**Comment by gumb0** [comment]
Sufficient statuses I think would be
- unmodified
- added_clear // modified for the first time the slot that was zero
- modified_clear // modified for the first time the slot that was non-zero
- modified_dirty

(Refunds for deleting are handled outside of VM in transaction finalization)

**Comment by chfast** [comment]
I will work on this.

**Comment by chfast** [comment]
I'm closing it as partly done in #52. The list would have to extended for EIP-1087, but nothing complicated is expected.
