### ISSUE TITLE
Add EVMC_ALIAS helper to declare symbol alias (e.g. evmc_create)

### ISSUE THREAD

**Issue by axic** [ethereum/evmc#86]

**Comment by chfast** [comment]
What exactly do you mean?

**Comment by axic** [comment]
```
EVMC_EXPORT struct evmc_instance* evmc_create_hera(void) EVMC_NOEXCEPT EVMC_ALIAS("evmc_create");
```

would create two exported functions:
- `evmc_create_hera`
- `evmc_create`

**Comment by chfast** [comment]
But what implementation do you have in mind?

**Comment by axic** [comment]
I am not fully sure anymore if we need this, perhaps if we suggest that shared libraries are the best way to distribute EVMC VMs and #81 is implemented then it is likely not needed.

**Comment by axic** [comment]
It seems the closest way doing this on MSVC is with a `#pragma` linker export statement, which wrapped into a macro is unlikely to work reliably.
